#Satellite private/public key
#Tue Jun 16 14:40:28 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCAiVPePXnINnhvwc5FwGI2VauOuw0lfz68ey/W+kBpTyA\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKAb8C9hGif00roYbvUqzVhEO65e/VCdWIyP3mwuW5u41L2XE++wT32NloRQtweu1hXVk9Uxmk0M5Nb7wFnEudA\=\=
