#Satellite public keys
#Mon Jun 15 16:34:02 CEST 2026
Service1=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQTX544Sr4QuWt6lCox1EXLV7y2ULDSZtSGQLnD5kQHes3SVxBYYPicO6W4XUT0x70oqkCLJL+1W0G9VrRleXLQ\=\=
Service2=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhth0EbTsPQl2xTWnYjH+K0H6TkjwwCQQJFEz8YGzxX3sNaatKi0FQYmQzeSoQqQmfxT9Af7rITIK/Ra2g2vhxw\=\=
Service3=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+33Le79tRCnOkxcyVjmpU25Xr+Ww8n3fEgesjU+HCjYpTWZJv8sCrZ8t0dHlt8MVd2l2HYm7yCabuGsMlTDTbg\=\=
Service4=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfiApU/vOEYfmH7zVWnuYKK65qr7TVcsGOG5amYrRLDcgzH1cIkppVu7SQbOBi+hFyYBqbQU6kQN9qW6kFcBSpw\=\=
Service5=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEamqD2gtdgTYve3vH/qXMCWP8LYHSV/tibDL7tdMm5zHZxRXlpK+Kk8qf917Vd2S07nqtxbZFYpe/u5xIl210Dw\=\=
Service6=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl8EVLKp/bsCMD2ZHr5+wKBDgAE6+TVZf+Y5RCuudLiD9JZgPV1e0EZQ3Omh/HivTIW7f0ZO+qMZ359R9AvEwZg\=\=
Service7=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWSEgq4rpgzKLKCQd8UncoviLVFbUc6RjP4d7+UDQkcYcfZBdeLT6NqoBKBYbgbWmB5KmVtUVng6vymhnaxT9vQ\=\=
