#Satellite public keys
#Tue Jun 16 14:57:26 CEST 2026
Service1=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQTX544Sr4QuWt6lCox1EXLV7y2ULDSZtSGQLnD5kQHes3SVxBYYPicO6W4XUT0x70oqkCLJL+1W0G9VrRleXLQ\=\=
Service2=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8FKgz3jCZG/cJzUVl0s9eRitqD3ecWUXgWclOSPRqihKc5ZEhyeSTZFGyD3Ue1UjtSK/mGxmostxIf0p9nnNEg\=\=
Service3=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+33Le79tRCnOkxcyVjmpU25Xr+Ww8n3fEgesjU+HCjYpTWZJv8sCrZ8t0dHlt8MVd2l2HYm7yCabuGsMlTDTbg\=\=
Service4=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKAb8C9hGif00roYbvUqzVhEO65e/VCdWIyP3mwuW5u41L2XE++wT32NloRQtweu1hXVk9Uxmk0M5Nb7wFnEudA\=\=
Service5=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2v/R6rwrUaIlju1chzMmcmYBEdJbUsR2wj640SF78ZTG2Xg0TlQM/WHXpm6r1VaAiaeFPYplP+GcAyveUtvWPw\=\=
Service6=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl8EVLKp/bsCMD2ZHr5+wKBDgAE6+TVZf+Y5RCuudLiD9JZgPV1e0EZQ3Omh/HivTIW7f0ZO+qMZ359R9AvEwZg\=\=
Service7=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWSEgq4rpgzKLKCQd8UncoviLVFbUc6RjP4d7+UDQkcYcfZBdeLT6NqoBKBYbgbWmB5KmVtUVng6vymhnaxT9vQ\=\=
