#Satellite private/public key
#Tue Jun 16 14:39:06 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCWoW419ifo42CIAWhfVNKU2CJaM4N5Go9OVoDNNV7XjQ\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8FKgz3jCZG/cJzUVl0s9eRitqD3ecWUXgWclOSPRqihKc5ZEhyeSTZFGyD3Ue1UjtSK/mGxmostxIf0p9nnNEg\=\=
