spring.application.name=Service3
server.port=8084
satellite.name=Service3
satellite.weight=1.0


# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

#  Logging
logging.level.com.example.service1=DEBUG
logging.level.org.springframework.amqp=INFO

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=${server.port}