spring.application.name=Service5
server.port=8086
satellite.name=Service5
satellite.weight=2.0

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

#  Logging
logging.level.com.example.service1=DEBUG
logging.level.org.springframework.amqp=INFO

