spring.application.name=Service7
server.port=8088
satellite.name=Service7
satellite.weight=0.9

# Fault Injection Configuration
fault.injection.crash=0.2


# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

#  Logging
logging.level.com.example.service1=DEBUG
logging.level.org.springframework.amqp=INFO

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=${server.port}
