#Satellite private/public key
#Mon Jun 15 16:33:53 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBpqxL5bpKERahw9UVSls5U4Bfkafi4TnSYdlR0bB/maw\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl8EVLKp/bsCMD2ZHr5+wKBDgAE6+TVZf+Y5RCuudLiD9JZgPV1e0EZQ3Omh/HivTIW7f0ZO+qMZ359R9AvEwZg\=\=
