#Satellite private/public key
#Mon Jun 15 16:33:50 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCDPqIIMdW8kNBPCmamIM4MMGM+bsNlgWyhKuwCfq+K5Lg\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+33Le79tRCnOkxcyVjmpU25Xr+Ww8n3fEgesjU+HCjYpTWZJv8sCrZ8t0dHlt8MVd2l2HYm7yCabuGsMlTDTbg\=\=
