#Satellite private/public key
#Mon Jun 15 16:33:59 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCAeRCfps5/VnVlhFsuRLrV7k3+YunrfZqGcGA7dZcOaMQ\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEamqD2gtdgTYve3vH/qXMCWP8LYHSV/tibDL7tdMm5zHZxRXlpK+Kk8qf917Vd2S07nqtxbZFYpe/u5xIl210Dw\=\=
