#Satellite private/public key
#Mon Jun 15 16:33:56 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCdl/uAUclhvzfjVGJVUwPGrc3dCUG7Z0hJ68i+Y1GfVQ\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWSEgq4rpgzKLKCQd8UncoviLVFbUc6RjP4d7+UDQkcYcfZBdeLT6NqoBKBYbgbWmB5KmVtUVng6vymhnaxT9vQ\=\=
