#Satellite private/public key
#Mon Jun 15 16:21:25 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCW2t/SwRMJiK1PgHZ7shMw+00ZKK51Ws35W5fHEWn6FQ\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQTX544Sr4QuWt6lCox1EXLV7y2ULDSZtSGQLnD5kQHes3SVxBYYPicO6W4XUT0x70oqkCLJL+1W0G9VrRleXLQ\=\=
