#Satellite private/public key
#Tue Jun 16 14:57:26 CEST 2026
privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCIblzYKgu7G+n9N4ppJv7J5QwC/SN1ACUfxmledegm0A\=\=
publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2v/R6rwrUaIlju1chzMmcmYBEdJbUsR2wj640SF78ZTG2Xg0TlQM/WHXpm6r1VaAiaeFPYplP+GcAyveUtvWPw\=\=
