spring.application.name=Service1
server.port=8082
satellite.name=Service1
satellite.weight=2.0

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

#  Logging
logging.level.com.example.service1=DEBUG
logging.level.org.springframework.amqp=INFO

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=${server.port}

